source 'http://rubygems.org'
ruby "~> 2.5.0"

# Specify specific gem source/location (e.g. github branch) for running bundle in this directory
# This is needed if the version of the gem you want to use is not on rubygems

gem 'openstudio-alfalfa', :github => 'NREL/openstudio-alfalfa-gem', branch: 'master'
